name: Sync labels

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - .github/labels/labels.yml

permissions:
  issues: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels/labels.yml
          delete-other-labels: false
